<?php

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array (
		'key' => 'group_581cf5b43752b',
		'title' => 'Workout',
		'fields' => array (
			array (
				'key' => 'field_581cf9cfaa33d',
				'label' => 'Movements',
				'name' => 'movements',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'button_label' => 'Add New Exercise',
				'min' => '',
				'max' => '',
				'layouts' => array (
					array (
						'key' => '5827bf587a06d',
						'name' => 'based_on_snatch',
						'label' => 'Based On Snatch',
						'display' => 'table',
						'sub_fields' => array (
							array (
								'key' => 'field_5827bf587a06e',
								'label' => 'Name',
								'name' => 'name',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5827bf587a06f',
								'label' => 'Sets',
								'name' => 'sets',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5827bf587a071',
								'label' => 'Reps',
								'name' => 'reps',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5827bf587a070',
								'label' => '% of 1RM',
								'name' => '%_of_1rm',
								'type' => 'number',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '%',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					array (
						'key' => '5827cc9795113',
						'name' => 'based_on_cleanjerk',
						'label' => 'Based On Clean & Jerk',
						'display' => 'table',
						'sub_fields' => array (
							array (
								'key' => 'field_5827cc9795114',
								'label' => 'Name',
								'name' => 'name',
								'type' => 'text',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5827cc9795115',
								'label' => 'Sets',
								'name' => 'sets',
								'type' => 'text',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5827cc9795116',
								'label' => 'Reps',
								'name' => 'reps',
								'type' => 'text',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5827cc9795117',
								'label' => '% of 1RM',
								'name' => '%_of_1rm',
								'type' => 'number',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '%',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					array (
						'key' => '5827cca495118',
						'name' => 'based_on_backsquat',
						'label' => 'Based On Backsquat',
						'display' => 'table',
						'sub_fields' => array (
							array (
								'key' => 'field_5827cca495119',
								'label' => 'Name',
								'name' => 'name',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5827cca49511a',
								'label' => 'Sets',
								'name' => 'sets',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5827cca49511b',
								'label' => 'Reps',
								'name' => 'reps',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5827cca49511c',
								'label' => '% of 1RM',
								'name' => '%_of_1rm',
								'type' => 'number',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '%',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					array (
						'key' => '582a304479830',
						'name' => 'based_on_frontsquat',
						'label' => 'Based On Front Squat',
						'display' => 'table',
						'sub_fields' => array (
							array (
								'key' => 'field_582a304479831',
								'label' => 'Name',
								'name' => 'name',
								'type' => 'text',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582a304479832',
								'label' => 'Sets',
								'name' => 'sets',
								'type' => 'text',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582a304479833',
								'label' => 'Reps',
								'name' => 'reps',
								'type' => 'text',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582a304479834',
								'label' => '% of 1RM',
								'name' => '%_of_1rm',
								'type' => 'number',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '%',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					array (
						'key' => '582a305779835',
						'name' => 'based_on_ohs',
						'label' => 'Based On Overhead Squat',
						'display' => 'table',
						'sub_fields' => array (
							array (
								'key' => 'field_582a305779836',
								'label' => 'Name',
								'name' => 'name',
								'type' => 'text',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582a305779837',
								'label' => 'Sets',
								'name' => 'sets',
								'type' => 'text',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582a305779838',
								'label' => 'Reps',
								'name' => 'reps',
								'type' => 'text',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582a305779839',
								'label' => '% of 1RM',
								'name' => '%_of_1rm',
								'type' => 'number',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '%',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					array (
						'key' => '582a306a7983a',
						'name' => 'based_on_ohp',
						'label' => 'Based On Overhead Press',
						'display' => 'table',
						'sub_fields' => array (
							array (
								'key' => 'field_582a306a7983b',
								'label' => 'Name',
								'name' => 'name',
								'type' => 'text',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582a306a7983c',
								'label' => 'Sets',
								'name' => 'sets',
								'type' => 'text',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582a306a7983d',
								'label' => 'Reps',
								'name' => 'reps',
								'type' => 'text',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582a306a7983e',
								'label' => '% of 1RM',
								'name' => '%_of_1rm',
								'type' => 'number',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '%',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					array (
						'key' => '582a30767983f',
						'name' => 'based_on_bench',
						'label' => 'Based On Bench Press',
						'display' => 'table',
						'sub_fields' => array (
							array (
								'key' => 'field_582a307679840',
								'label' => 'Name',
								'name' => 'name',
								'type' => 'text',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582a307679841',
								'label' => 'Sets',
								'name' => 'sets',
								'type' => 'text',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582a307679842',
								'label' => 'Reps',
								'name' => 'reps',
								'type' => 'text',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582a307679843',
								'label' => '% of 1RM',
								'name' => '%_of_1rm',
								'type' => 'number',
								'instructions' => '',
								'required' => '',
								'conditional_logic' => '',
								'wrapper' => array (
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '%',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					array (
						'key' => '582a308479844',
						'name' => 'based_on_deadlift',
						'label' => 'Based On Deadlift',
						'display' => 'table',
						'sub_fields' => array (
							array (
								'key' => 'field_582a308479845',
								'label' => 'Name',
								'name' => 'name',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582a308479846',
								'label' => 'Sets',
								'name' => 'sets',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582a308479847',
								'label' => 'Reps',
								'name' => 'reps',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582a308479848',
								'label' => '% of 1RM',
								'name' => '%_of_1rm',
								'type' => 'number',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '%',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
				),
			),
			array (
				'key' => 'field_5829ec37d81b4',
				'label' => 'Restrict Content By User',
				'name' => 'user',
				'type' => 'user',
				'instructions' => 'Please include yourself in the list of users, otherwise you won\'t be able to view the content',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'role' => '',
				'allow_null' => 1,
				'multiple' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'workout',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'custom_fields',
		),
		'active' => 1,
		'description' => 'Start by choosing which 1RM your exercise is based on',
	));

endif;